services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leanguard_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro
